# Generated by Django 4.1.2 on 2022-10-31 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_folder_owner_alter_folder_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_folder', to='vault.folder'),
        ),
    ]
