# Generated by Django 4.1.2 on 2022-11-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0003_alter_entry_folder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uri",
            old_name="entry",
            new_name="reference",
        ),
    ]
